name: Release on Release Branch

on:
  push:
    branches:
      - "release/*"

# The different jobs of this workflow need the following permissions
permissions:
  contents: write
  pull-requests: write
  repository-projects: read
  # only required for workflows in private repositories
  actions: read

concurrency:
  group: release

jobs:
  # This job creates the necessary labels for the release-please PRs:
  # https://github.com/googleapis/release-please-action/issues/1074

  # This job creates a release pull request
  # and provides the necessary outputs for the subsequent jobs
  release-prep:
    name: Create Release Pull Request
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - id: release
        name: Run release release-please
        uses: googleapis/release-please-action@v4
        with:
          config-file: ".github/release-config.json"
          manifest-file: ".github/release-manifest.json"
          # token: ${{ secrets.GH_TOKEN }}
          target-branch: ${{ github.ref_name }}

  # This job runs tests before the creation of the prerelease
  release-test:
    name: Run Release Tests
    runs-on: ubuntu-latest
    if: ${{ needs.release-prep.outputs.releases_created == 'false' }}
    needs: [release-prep]
    steps:
      - name: Release Build Push Deploy
        run: |
          echo "Release Tests"
